console.log("trabalhando com atribuição de variveis");
let nome = "Fernando";
const sobrenome = "Sousa";

//console.log(nome + " " + sobrenome)
console.log(nome, sobrenome)
console.log(`meu nome é ${nome} ${sobrenome}`);

let contador = 0;
contador = contador + 1;

const nomeCompleto = PrimeiroNome + sobrenome;
console.log(nomeCompleto);

let idade; //declarando variável
idade: 26 //atribuindo valor